version: 2

models:
  - name: fact_world_earthquake
    description: >
      List of workd earthquake data for data-mart.
    columns:
      - name: time
        description: "timestamp"
        tests:
          - not_null
