name: Build and Push Flows Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev or prod)'     
        required: true
        options:
          - dev
          - prod
        default: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ vars.ARTIFACT_REGISTRY_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud --quiet auth configure-docker europe-west3-docker.pkg.dev

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/prefect-flows/Dockerfile
        push: true
        tags: europe-west3-docker.pkg.dev/${{ vars.ARTIFACT_REGISTRY_PROJECT_ID }}/world-earthquake-pipeline/prefect-flows